force-app/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{00000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <referenceTo>Item__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RateOrderController.cls
public without sharing class RateOrderController {
    public String orderId {get;set;}
    public Order__c orderRec {get;set;}

    public Boolean needsRating {get;set;}

    public RateOrderController() {
        orderId = ApexPages.currentPage().getParameters().get('id');
        
        //Query for the order
        orderRec = [SELECT Id, Rating__c, Item__r.Name, Order_Number__c FROM Order__c WHERE Id = :orderId];

        if (orderRec.Rating__c == null) {
            needsRating = true;
        } else {
            needsRating = false;
        }
    }

    @RemoteAction
    public static void rateOrder(Id orderId, String rating) {
        Integer ratingVal = Integer.valueOf(rating);

        Order__c toUpdate = new Order__c(Id = orderId, Rating__c = ratingVal);
        update toUpdate;
    }
}