force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Item__c/fields/Average_Rating__c.field-meta.xml
<CustomField>
    <fullName>Average_Rating__c</fullName>
    <formula>Total_Rating__c / Num_of_Rated_Orders__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Average Rating</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <label>Section</label>
    <referenceTo>Section__c</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Out of Stock</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{00000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <referenceTo>Item__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_Finished__c.field-meta.xml
<CustomField>
    <fullName>Order_Finished__c</fullName>
    <label>Order Finished</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_Placed__c.field-meta.xml
<CustomField>
    <fullName>Order_Placed__c</fullName>
    <inlineHelpText>When the order was placed.</inlineHelpText>
    <label>Order Placed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Section</label>
    <referenceTo>Section__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Out of Stock</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Section__c/Section__c.object-meta.xml
<CustomObject>
    <label>Section</label>
    <nameField>
        <label>Event Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Section__c/fields/Average_Rating__c.field-meta.xml
<CustomField>
    <fullName>Average_Rating__c</fullName>
    <formula>Total_Rating__c /  Num_of_Rated_Items__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Average Rating</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Section__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Sections</relationshipLabel>
    <relationshipName>Sections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/OverviewController.cls
public class OverviewController {
	public Event__c eventRecord { get; set; }
	public List<PageSection> sections { get; set; }

	public OverviewController() {
		String eventId = ApexPages.currentPage().getParameters().get('id');

		eventRecord = [SELECT Id, Name FROM Event__c WHERE Id = :eventId];

		createSections();
	}

    public void createSections() {
        List<Section__c> sectionRecords = [
			SELECT Id, Name, Average_Rating__c, (SELECT Id, Name FROM Items__r ORDER BY Average_Rating__c DESC NULLS LAST), (SELECT Id, Name, Item__r.Name, Order_Number__c, Contact__r.Name, Order_Placed__c, Order_Finished__c, Status__c FROM Orders__r ORDER BY CreatedDate ASC)
			FROM Section__c
			WHERE Event__c = :eventRecord.Id
		];


        sections = new List<PageSection>();

        for (Section__c sectionRecord : sectionRecords) {
            PageSection newSection = new PageSection();
            newSection.sectionRecord = sectionRecord;


            for (Order__c order : sectionRecord.Orders__r) {
                newSection.totalOrders++;

                if (order.Status__c == 'New') {    
                    newSection.newOrders.add(new OrderObj(order));
                } else {
                    newSection.completeOrders++;

                    if (order.Order_Finished__c != null && order.Order_Placed__c != null) {
                        newSection.totalTime += (Long)(order.Order_Finished__c - order.Order_Placed__c);
                        newSection.finishedCount++;
                    }
                }
                
            }

            if (newSection.finishedCount > 0) {
                newSection.averageTime = Utils.formatTime(newSection.totalTime / newSection.finishedCount);
            } else {
                newSection.averageTime = 'N/A';
            }

            sections.add(newSection);
        }
    }

    public class PageSection {
        public Section__c sectionRecord {get;set;}
        public List<OrderObj> newOrders {get;set;}
        public Integer totalOrders {get;set;}
        public Integer completeOrders{get;set;}

        public Long totalTime;
        public Integer finishedCount;
        public String averageTime {get;set;}

        public PageSection() {
            newOrders = new List<OrderObj>();
            totalOrders = 0;
            completeOrders = 0;
            totalTime = 0;
            finishedCount = 0;
        }
    }

    public class OrderObj {
        public Order__c orderRecord {get;set;}
        public Item__c itemRecord {get;set;}
        public Contact contactRecord {get;set;}
        public String timeInFlight {get;set;}

        public OrderObj(Order__c record) {
            orderRecord = record;
            itemRecord = record.Item__r;
            contactRecord = record.Contact__r;

            timeInFlight = getTimeInFlight((Long)orderRecord.Order_Placed__c);

        }

        public String getTimeInFlight(Long startTime) {
            Long timeBetween = Datetime.now().getTime() - startTime;

            return Utils.formatTime(timeBetween);
        }
    }

}